language: go
go:
- 1.11.x
install:
  - godep save ./...
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/tools/godep
  - go get github.com/gorilla/websocket
  - go get golang.org/x/tools/cmd/cover
deploy:
  provider: heroku
  app: public-go-websockets-prod
  on:
    repo: ncmd/public-golang-websockets-app
    branch: master
  api_key:
    secure: ZIIivqmiYXwSalJWfabRizNvKaT56E3znMUyNd9Nq0VfUMAoZl4bIUY8tFhsEtEdNpyrwwglv2ced9PDar/GWXPHFzkS078CIJQArsbBGU9ZObQq/eIU2WYC66D7ctwd86m/C5gZra8K2tTFIKHh7JDKd4tzwcuB50gUe6yZxln9qClgU6cUuMDkCFCpSK7xGjk+LPUXhAQFC+D0FKqZdGUWuOuMVpDRIc/JUUHFLbIPYMLY5U9Tnhtg+IMYNdaqUpXbBcetN9FrtHExh2ZJ6vVsW/uAdcneHJLUiBXti7twB+Y7Na6NFZ1I9ptNocdrqOUPOpmYPRqgmY9OEVUn+lgwUgzYSNipchZm4HCzyRNg8lrk5N4uSnWfNxpTA3e8AfK3VbyLKPKl8/ytzHzK5fcZu1raaP/m+OW1nCjxIgLd4qUpobvsgkYmdlFM5gMKXriJpoPODSA3yWVmy74nXNDgoy+brJ3GFYSsERCqtbaY0De8/+CuEdYB13O3Xrj07BwRcdlJDadNvWN7RFjkkfkWyvcHBpvFUiZ5FPTzI1+pbqd8FoMNeMbYKkxIbxKJ7fI3chpM/5SnmiCO8NirYLE6iSRHBSgBHKDoBYLvJOw8LonhKUhPrNPhh8F6jbD/dGxnRAHddDLlVIVHL7sywBS2tvmL7vbE9J4Eo3f0PxI=
env:
  APP_ENV: prod