language: go
go:
- 1.11.x
go_import_path: "$HOME/go/src/public/public-golang-websockets-app"

deploy:
  provider: heroku
  app: public-go-websockets-prod
  on:
    condition: "$TRAVIS_GO_VERSION =~ ^1\\.11"
    repo: ncmd/public-golang-websockets-app
    branch: master
  api_key:
    secure: ZIIivqmiYXwSalJWfabRizNvKaT56E3znMUyNd9Nq0VfUMAoZl4bIUY8tFhsEtEdNpyrwwglv2ced9PDar/GWXPHFzkS078CIJQArsbBGU9ZObQq/eIU2WYC66D7ctwd86m/C5gZra8K2tTFIKHh7JDKd4tzwcuB50gUe6yZxln9qClgU6cUuMDkCFCpSK7xGjk+LPUXhAQFC+D0FKqZdGUWuOuMVpDRIc/JUUHFLbIPYMLY5U9Tnhtg+IMYNdaqUpXbBcetN9FrtHExh2ZJ6vVsW/uAdcneHJLUiBXti7twB+Y7Na6NFZ1I9ptNocdrqOUPOpmYPRqgmY9OEVUn+lgwUgzYSNipchZm4HCzyRNg8lrk5N4uSnWfNxpTA3e8AfK3VbyLKPKl8/ytzHzK5fcZu1raaP/m+OW1nCjxIgLd4qUpobvsgkYmdlFM5gMKXriJpoPODSA3yWVmy74nXNDgoy+brJ3GFYSsERCqtbaY0De8/+CuEdYB13O3Xrj07BwRcdlJDadNvWN7RFjkkfkWyvcHBpvFUiZ5FPTzI1+pbqd8FoMNeMbYKkxIbxKJ7fI3chpM/5SnmiCO8NirYLE6iSRHBSgBHKDoBYLvJOw8LonhKUhPrNPhh8F6jbD/dGxnRAHddDLlVIVHL7sywBS2tvmL7vbE9J4Eo3f0PxI=
env:
  APP_ENV: prod
