language: go
go:
- 1.11.x
go_import_path: "$HOME/go/src/public/public-golang-websockets-app"
deploy:
  provider: heroku
  app: public-go-websockets-prod
  on:
    condition: "$TRAVIS_GO_VERSION =~ ^1\\.11"
    repo: ncmd/public-golang-websockets-app
    branch: master
  api_key:
    secure: AgguBxznHwuoL2HU/mNJalzxUTKhCs9y+QzX1pQOnf4VYEAy8slVHzBSKjGwuFbNw1AayOzWqYlHItrJr8lNCjfYmAkt1sRdAgNgMnqGG0xVBMIMfDijKO1tbOHIJAfp1beLxNYtMkweLx4GRL4kQpvRtE+urNa809AW3VR2DLvWUMUoiB3cIc3BnFHPyMzSp2mlsN5blRNgm5OBt8o13Ns4bUDWF+vlyKw7xwoeQXLGFF73VdZX3JZVecXulpnc8Po40ZkpSy4f1r46xmfSbs2hUsP4gO9u731SlFI4EQtVpRiqZEtnDePqJ9WgqcIr0ryUbs66x2XKSDhe/HKL03E3wozjYj+epKdxhI19YRjITCKOzohx0Hf5VhsH7C7xOow4fSVg83MRCiVWYoGiPGPvK5JilChw74c+JhL/ITM4sP4In4s/QWw3S+J89cjii5AV9c4XWJGq+kAjMOjnySuX33EOT+LCyFnWbtptSxUMLd0VXYTvKktrnExqQZ7CdDbR10xEGsX5JGMiIg9YKgt9CyGDNLU9lYbbLifsIgJD+ej5bE1iIhmExzU7Yh7ACARP/IbgwqungR9ewv5hx6lQo2PBS7xsdcbnSONwzzq/NRS8nrHxkJcG6c/ZG7bUlEPBmEsmKNg4RbCzIK2fnPwWnRpyajSHwWJJV38XQc0=
env:
  APP_ENV: prod
