language: go
go:
- 1.11.x
go_import_path: "$HOME/go/src/public/public-golang-websockets-app"
deploy:
  provider: heroku
  app: public-go-websockets-prod
  on:
    condition: "$TRAVIS_GO_VERSION =~ ^1\\.11"
    repo: ncmd/public-golang-websockets-app
    branch: master
  api_key:
    secure: WyNddzIU8+2jO8frQYHW1BFXWj1LurPUot1xE9aCcwpU6UX8i7DG3HxSVxh5xO8XjiQYqV8kGqyXvvIOHaZw2YdflwBX3P92FYDN0fH3F0ULDhUXgb+WxbXm0T/tHP+2w0zMDw2pnLgOksjTkmon4bd35Z7FmD1UYMQllh/KWutifFLIdh0om3DDRN0V4Hos98JSttynk81aXRHX/2Xe5Dzf0fLj298XAVCp9WJC/eOgf8h9LX1TCPZA8ZC6GcrWR90Iw7CeebrP8krBkXtTf0UjHdzESABHwSknEsymXLVZOteAwxl4PlmvQXxQPgXo0itVFx1XbXTqYm+ZROHgSvSqJgxlo5Rgh4VlwAbwUjgsoX72g8gXUcMZ7C3g87Pnk/sbAazx9g8tF9YDjrpcdkVAn07IbYD0QNdF6btUISczrwfDPE6faLqAWGAoVgjiu8sL8Lgmk8RRf5dO5olOVUGYoD3KFDi4+8wH9gOj4NvIir/5jd15VWPfd4XCpUEqI9PeccLepaCGOl7kaE/YWVb06I0oMQzDa9koEp5qR5X/z25P/V4V1lVa1XTxfrZCLycRcgDreqvdElVgpoVAxoFoixKg7Vqv4Goc1jIf48usn9jwqd2+3+ZH6UN5kxHynNytkycKomw1r19dq+5+UxGux2DTTTBEf7BuWu4UB4M=
env:
  APP_ENV: prod
